name: Publish to PyPI

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install Poetry
        run: pipx install poetry==2.1.4

      - name: Configure PyPI Token
        env:
          PYPI_TOKEN: ${{ secrets.POETRY_PYPI_TOKEN_PYPI }}
        run: poetry config pypi-token.pypi "$PYPI_TOKEN"

      - name: Publish displaypad-driver
        working-directory: packages/driver
        run: poetry publish --build --no-interaction

      - name: Publish displaypad-lib
        working-directory: packages/library
        run: poetry publish --build --no-interaction
